c2.1

diff --git a/.github/workflows/premier_workflow.yaml b/.github/workflows/premier_workflow.yaml
--- a/.github/workflows/premier_workflow.yaml
+++ b/.github/workflows/premier_workflow.yaml
@@ -1,23 +1,27 @@
 name: Toto
-on: [push]
+on:
+  push:
+    branches:
+      - "dev"
 jobs:
   Test:
     runs-on: ubuntu-latest
     steps:
       - name: Test 1
-        run: exit 1
-  Create-issue:
-    needs: [Test]
-    runs-on: ubuntu-latest
-    if: always() && (needs.Test.result == 'failure')
-    steps:
-      - name: create issue
-        uses: actions-ecosystem/action-create-issue@v1
-        with:
-          github_token: ${{ secrets.GITHUB_TOKEN }}
-          title: Problème lors du test 1
-          body: |
-            ## a faire ##
-            Tout a pété!!!
-      - name: afficher secrets
-        run: echo ${{ secrets.ToTo }}
+        run: echo "Salut"
+  #       run: exit 1
+  # Create-issue:
+  #   needs: [Test]
+  #   runs-on: ubuntu-latest
+  #   if: always() && (needs.Test.result == 'failure')
+  #   steps:
+  #     - name: create issue
+  #       uses: actions-ecosystem/action-create-issue@v1
+  #       with:
+  #         github_token: ${{ secrets.GITHUB_TOKEN }}
+  #         title: Problème lors du test 1
+  #         body: |
+  #           ## a faire ##
+  #           Tout a pété!!!
+  #     - name: afficher secrets
+  #       run: echo ${{ secrets.ToTo }}
